;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
;                               Main
;       author  : terrynini
;       created :  2017/05/02
;       updated :
;       version : 0.2
;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
;IFNDEF MAIN_INC
;MAIN_INC equ <1>
;ENDIF

public OptionTexture
public CurrentKeystate
public SE_Cusor
public SE_Confirm
public gRender
public Camera